@startuml
'https://plantuml.com/sequence-diagram

autonumber

SolutionRandom -> Utility: generateRandomColor()
SolutionRandom <-- Utility: Color couleur

SolutionRandom -> inputImage : getRGB(x, y)
SolutionRandom <-- inputImage : int rgb

SolutionRandom -> Utility : findClosestColorIndex(color, colors);
SolutionRandom <-- Utility : int index

SolutionRandom -> outputImage : setRGB(x, y, closestColor.getRGB())
SolutionRandom <-- outputImage

SolutionRandom -> Distance : distance(inputImage, outputImage)
SolutionRandom <-- Distance : long distance

SolutionRandom -> ImageIO : write(bestImage, "png", new File(outputImagePath))
SolutionRandom <-- ImageIO

@enduml