@startuml
'https://plantuml.com/sequence-diagram

autonumber

SolutionRandomV2 -> Utility: generateRandomColor()
SolutionRandomV2 <-- Utility: Color couleur

SolutionRandomV2 -> inputImage : getRGB(x, y)
SolutionRandomV2 <-- inputImage : int rgb

SolutionRandomV2 -> Utility : findClosestColorIndex(color, colors);
SolutionRandomV2 <-- Utility : int index

SolutionRandomV2 -> outputImage : setRGB(x, y, closestColor.getRGB())
SolutionRandomV2 <-- outputImage

SolutionRandomV2 -> Distance : distance(inputImage, outputImage)
SolutionRandomV2 <-- Distance : long distance

SolutionRandomV2 -> ImageIO : write(bestImage, "png", new File(outputImagePath))
SolutionRandomV2 <-- ImageIO

@enduml